Algoritmo "ExercicioSaidaDados"

Var

   produto1: caractere
   produto2: caractere
   preco1: real
   preco2: real
   idade: inteiro
   genero: caractere
   codigo: inteiro

Inicio

      produto1 <- "Computador"
      produto2 <- "TV"
      preco1 <- 2100.5
      preco2 <- 1830.0
      idade <- 30
      codigo <- 5291
      genero <- "F"
      
      escreval("O produto")

Fimalgoritmo